# Generated by Django 4.2 on 2024-06-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0004_rename_phonenumber_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='validity_date',
            new_name='validate_date',
        ),
    ]
