# Generated by Django 4.2 on 2024-06-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0008_eventattendent_requisition_verification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vvip.district'),
        ),
        migrations.AddField(
            model_name='eventattendent',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vvip.thana'),
        ),
    ]
