# Generated by Django 4.2 on 2024-06-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0009_eventattendent_district_eventattendent_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendent',
            name='print_status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attendent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vvip.eventattendent')),
            ],
        ),
    ]
