# Generated by Django 4.2 on 2024-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0010_eventattendent_print_status_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
