# Generated by Django 4.2 on 2024-06-28 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0013_sb_attendent_user_sb_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sb_attendent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sb_attendent',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
