# Generated by Django 4.2 on 2024-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0014_sb_attendent_created_alter_sb_attendent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sb_attendent',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='picture-gallary-upload/%Y/%m/%d/'),
        ),
    ]
