# Generated by Django 4.2 on 2024-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0015_alter_sb_attendent_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sb_attendent',
            name='print_status',
            field=models.IntegerField(default=0),
        ),
    ]
