# Generated by Django 4.2 on 2024-06-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvip', '0018_remove_color_template_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sb_attendent',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vvip.agency'),
        ),
        migrations.AddField(
            model_name='sb_attendent',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vvip.requisition'),
        ),
    ]
